-- Add HR fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'Nederland';

ALTER TABLE users ADD COLUMN IF NOT EXISTS employment_end_date TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_fixed_term_contract BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS contract_hours_per_week DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS annual_leave_days_or_hours DOUBLE PRECISION;

ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact_relation TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact_phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact_email TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS hr_notes TEXT;
